#!/usr/bin/env tsx
// NO-BUN: Converted from Bun.file() to Node.js fs/promises

import { readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))

const colors = await readFile(join(__dirname, "colors.txt"), "utf-8")

const variables = []
for (const line of colors.split("\n")) {
  if (!line.trim()) continue
  const [variable] = line.trim().split(":")
  const name = variable!.trim().substring(2)
  variables.push(`--color-${name}: var(--${name});`)
}

const output = `
/* Generated by script/tailwind.ts */
/* Do not edit this file manually */

@theme {
  --color-*: initial;
  ${variables.join("\n  ")}
}
`

await writeFile(join(__dirname, "../src/styles/tailwind/colors.css"), output.trim())
